name: "TGCF Telegram Forward"
description: "TGCF 1.1.7"
version: "1.1.7"
slug: "tgcf"
url: https://github.com/aahnik/tgcf/
init: false
hassio_api: true
hassio_role: homeassistant
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
webui: http://[HOST]:[PORT:8501]
ports:
  8501/tcp: 8501

map:
  - addon_config:rw
  - config:rw
  - data:rw
  - ssl

image: aahnik/tgcf/
